language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
addons:
  sonarqube:
    organization: bingoohuang-github
    token:
      secure: Q0b81ebLGrl8/lhQVwnPz+yOWMYqsI3QK4PjwPT8GPmbA47cs8oHiZDTm40mAb5lUvd1jkcMhmnG35ywIKoQswnkvCJdSYfSdmajXVALKB5I6sVSILec3TtZVfzahIScXi3C0wvUg8X0av9bj7L5qqi76sxGfAeSw/qp9/HCHtnB/H/98LIoCqf5pfqaSfGQP0i7JRq99U/9hFSdQ4cXJi7P1OD3LTcvfCL83XGSVoWydh8eSVDqRzsV7zZEPPpE7MNoMCgwot3SJashK7zYaMIU+9ML1mW31ncujHkF+zIBEELtU9aaymhPZSqeAqtTT+JCBdq8tgEx3Ikt2dWs38iq9bSaIP3bLMRpfEEh1ylBo6+eo8Oq3aVnfzWvdYfehcEKftUj3ePSBbO+CMWFddWOeFd7GWCBSE4RDE2tsvyBdefbsH0Nm5fy4U7HgEWMvzVz5FQTUIFvxgW67gL9U/HFBlPQfH1+oVV3+sbCpxv/jbAHiqMkB7UKNV6i+2mTpQH180JTO36J3fvKOKHPhRmvZ+AmbT5ehXrlb9qk7xZvEsXK5JogXYRX5bYB5Vqd+IJLFx5BFxkZoftgH2wz9ZpwBi090lOJrPq+sjW8qCpBS/lqvap4Y6ZoeQLg7sjmTIqLb4CN4EGlf39Z0YREfyXLxlcnbmajOhgly+X4hhE=
script:
- mvn clean test jacoco:report coveralls:report install sonar:sonar
env:
  global:
    secure: l9tSnitAH3S7wL9rmCrJ4bXa41x6yrA0eghn4FoaYZvsQGAWb4C3JVfmbsGWKjdAcngUYChMNw5HnlSPTy7z5U9gZNa6n23G48qGo/R5H+rHG+8nFgCJjh+xeN2m84L/EaPH2c+HW6rVJaGWjHV1lFj80grOP0J51M7qiwEPkBbCgF6vFqDZjqG2BMZwzO0uAqrS6b1SoChUaL2PROFKiXheARuUWbkYpWNq1mWeIMoPrv4WZDWOxuhjvmAFB93mq73Iv3WA+sdvyD7j8oKnlBBeC5wHuFl/1NGVbJ36OQh631l1XSJNB+nMtHhPCOS+Kq1Uxwl/NehAF1pXsYYKAzfYR8s+b42wFt8lEDihFU/dIpSpapVmPVyJVxw2vzcZxcLF9SJuCgbNUpgM4h9CA9pV8FoLk7Rrpa7nF8YTaBsj/rtCJKWtDnQYY/meWalkWmEVYEdu9sB3+ZieTA9I3ytFzxGcoiyvtUbOrDhmFdquLe+dLNoCgbniU79udkmQPksTVkcPA4UfwaHVYs6xHIdUdYaZiWxkR4l5OUJwlHD4g6CgCkOnLt3eTdU0zvlp61FxNjeZ7TxghdR5GO12F/LIaNFi36ouxdx9soW0/WVtvfXFMgI2X9PL5tNLxkr62JUNDhzndxFM1CQ+j5MiIJE4fDzXfVu22AgpPMx+xw8=
